/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuuuu_wavplayer_MainActivity */

#ifndef _Included_com_liuuuu_wavplayer_MainActivity
#define _Included_com_liuuuu_wavplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuuuu_wavplayer_MainActivity
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liuuuu_wavplayer_MainActivity_play
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
